### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by philsinatra** [isabellatognini/IDM222--Winter-2017#1]
> I'm still having issues. I know you told me to put "flex-direction: column" under .flex-container and .flex-container ul, but I just couldn't figure out how to get it back to the horizontal bar. Am I anywhere close to where I need to be? I'm still struggling with stacking the nav items after min width of 550px 

You're not fully implementing a solution. It looks like you're [copying part of one of my examples](https://github.com/isabellatognini/IDM222--Winter-2017/blob/0e13cbecc85e8392e159ab1aea627b05e585973e/website/style3.css#L66-L71).

This is a concept, not a solution for you to copy paste:

```css
.flex-container {
  display: flex;
  flex-direction: column;
}
```

The direct children of `.flex-container` will stack in a column.

---

```css
@media screen and (min-width: 550px) {
  .flex-container {
    flex-direction: row;
  }
}
```

At 550px, the direct children of `.flex-container` will line up in a row.

---

You should be using the same concept to deal with the `h2` and `ul` elements, and also on the `li` elements within the `ul`. This means that `.flex-container` and the `ul` will both act as _flex parent_ containers. It just so happens that the `ul` is also a direct child of `flex-container`.

Use [week5/example3](https://philsinatra.github.io/IDM222/examples/week5/ex003.html) as a sample. Look at [the CSS](https://github.com/philsinatra/IDM222/blob/dc96bc75a135f7bd92028ce4f45a891c47357d64/examples/week5/css/ex003.css) and try to understand how you are changing properties within media queries to get the effect you're looking for.

Make it work in a column first, which you already have. Then setup a media query and change the properties to change how the content is displayed.

**Comment by philsinatra** [comment]
> Okay, so I figured out the picture and text. I'm still stuck on the nav bar though. I added the media quieries for the nav like I did for the image and text. But it doesn't seem to be doing the same thing.

You're close. Examine [this block of code](https://github.com/isabellatognini/IDM222--Winter-2017/blob/ea9472597847a35c988337580981a45c2cb8848b/website/style3.css#L72-L80) from your stylesheet.

```css
@media all and (max-width: 600px) {
 .flex-container ul {
    -webkit-flex-direction: column;
    flex-direction: column;}}

 @media all and (min-width: 600px) {
 .flex-container ul {
    -webkit-flex-direction: row;
    flex-direction: row;}}
```

The first thing to notice is your selector in both media queries is exactly the same:

```css
 .flex-container ul {
```

You probably meant for one to include the `ul` and one not to include it. Next, notice the `flex-direction` property for each - one is set to `column` and the other `row`. You would want both to be set to `row` since we're dealing with a larger break point.

Last, you can group these together to simplify your code:

```css
@media all and (max-width: 600px) {
 .flex-container, 
 .flex-container ul {
    /* You don't need the -webkit- syntax anymore, it's obsolete. */
    /*-webkit-flex-direction: row;*/
    flex-direction: row;
  }
}
```
